# roles/base/handlers/main.yml

#- name: Reiniciar servicio SSH
#  service:
#    name: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"
#    state: restarted

# roles/base/handlers/main.yml
---
- name: Reiniciar SSH si cambió MOTD
  service:
    name: ssh
    state: restarted
  listen: Reiniciar SSH si cambió MOTD
  when: ansible_facts['os_family'] == "Ubuntu" or ansible_facts['os_family'] == "RedHat"
